version: '3.8'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Docker/dockerfile
    port:
      - 3000:3000
    volumes:
      - .:/app
    command: npm start
    networks:
      - webnet

networks:
  - webnet
